# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twi_acc', models.CharField(max_length=30)),
                ('twi_id', models.CharField(max_length=30)),
                ('img_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VdoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twi_acc', models.CharField(max_length=30)),
                ('twi_id', models.CharField(max_length=30)),
                ('vdo_name', models.CharField(max_length=30)),
            ],
        ),
    ]
