# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twi_acc', models.CharField(max_length=30)),
                ('twi_id', models.CharField(max_length=30)),
                ('retwi', models.CharField(max_length=10)),
                ('fav', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=80)),
            ],
        ),
    ]
