# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0004_remove_statusinfo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinfo',
            name='imgurl',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
