# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0005_statusinfo_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinfo',
            name='fav',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='retwi',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='twi_id',
            field=models.CharField(max_length=30),
        ),
    ]
