# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0006_auto_20171001_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=30)),
                ('twi_id', models.CharField(max_length=30)),
                ('retwi', models.CharField(max_length=30)),
                ('fav', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=140)),
                ('imgurl', models.CharField(max_length=80)),
            ],
        ),
    ]
