# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0010_artpaintchosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPainters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=30)),
                ('first', models.CharField(max_length=30)),
                ('hyphenname', models.CharField(max_length=30)),
                ('onename', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=140)),
            ],
        ),
    ]
