# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0016_stagefirst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagefirst',
            name='fav',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stagefirst',
            name='retwi',
            field=models.IntegerField(max_length=10),
        ),
    ]
