BEGIN TRANSACTION;
CREATE TABLE "twipic_vdoinfo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "twi_acc" varchar(30) NOT NULL, "twi_id" varchar(30) NOT NULL, "vdo_name" varchar(30) NOT NULL);
CREATE TABLE "twipic_statusinfo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "twi_acc" varchar(30) NOT NULL, "retwi" varchar(30) NOT NULL, "fav" varchar(30) NOT NULL, "desc" varchar(140) NOT NULL, "imgurl" varchar(80) NOT NULL, "twi_id" varchar(30) NOT NULL);
CREATE TABLE "twipic_imginfo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "twi_acc" varchar(30) NOT NULL, "twi_id" varchar(30) NOT NULL, "img_name" varchar(30) NOT NULL);
CREATE TABLE "twipic_firstinput" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file_name" varchar(100) NOT NULL);
CREATE TABLE "twipic_artpaintedt" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "que" varchar(30) NOT NULL, "twi_id" varchar(30) NOT NULL, "retwi" varchar(30) NOT NULL, "fav" varchar(30) NOT NULL, "desc" varchar(140) NOT NULL, "imgurl" varchar(80) NOT NULL);
CREATE TABLE "twipic_artpaint" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "que" varchar(30) NOT NULL, "twi_id" varchar(30) NOT NULL, "retwi" varchar(30) NOT NULL, "fav" varchar(30) NOT NULL, "desc" varchar(140) NOT NULL, "imgurl" varchar(80) NOT NULL);
CREATE TABLE "photologue_watermark" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(30) NOT NULL UNIQUE, "description" text NOT NULL, "image" varchar(100) NOT NULL, "style" varchar(5) NOT NULL, "opacity" real NOT NULL);
CREATE TABLE "photologue_photosize" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(40) NOT NULL UNIQUE, "width" integer unsigned NOT NULL, "height" integer unsigned NOT NULL, "quality" integer unsigned NOT NULL, "upscale" bool NOT NULL, "crop" bool NOT NULL, "pre_cache" bool NOT NULL, "increment_count" bool NOT NULL, "effect_id" integer NULL REFERENCES "photologue_photoeffect" ("id"), "watermark_id" integer NULL REFERENCES "photologue_watermark" ("id"));
CREATE TABLE "photologue_photoeffect" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(30) NOT NULL UNIQUE, "description" text NOT NULL, "transpose_method" varchar(15) NOT NULL, "color" real NOT NULL, "brightness" real NOT NULL, "contrast" real NOT NULL, "sharpness" real NOT NULL, "filters" varchar(200) NOT NULL, "reflection_size" real NOT NULL, "reflection_strength" real NOT NULL, "background_color" varchar(7) NOT NULL);
CREATE TABLE "photologue_photo_sites" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo_id" integer NOT NULL REFERENCES "photologue_photo" ("id"), "site_id" integer NOT NULL REFERENCES "django_site" ("id"));
CREATE TABLE "photologue_photo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "date_taken" datetime NULL, "view_count" integer unsigned NOT NULL, "crop_from" varchar(10) NOT NULL, "slug" varchar(250) NOT NULL UNIQUE, "caption" text NOT NULL, "date_added" datetime NOT NULL, "is_public" bool NOT NULL, "effect_id" integer NULL REFERENCES "photologue_photoeffect" ("id"), "title" varchar(250) NOT NULL UNIQUE);
CREATE TABLE "photologue_gallery_sites" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "gallery_id" integer NOT NULL REFERENCES "photologue_gallery" ("id"), "site_id" integer NOT NULL REFERENCES "django_site" ("id"));
CREATE TABLE "photologue_gallery_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "gallery_id" integer NOT NULL REFERENCES "photologue_gallery" ("id"), "sort_value" integer NOT NULL, "photo_id" integer NOT NULL REFERENCES "photologue_photo" ("id"));
CREATE TABLE "photologue_gallery" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_added" datetime NOT NULL, "slug" varchar(250) NOT NULL UNIQUE, "description" text NOT NULL, "is_public" bool NOT NULL, "title" varchar(250) NOT NULL UNIQUE);
CREATE TABLE "django_site" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "domain" varchar(100) NOT NULL UNIQUE);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id"), "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "action_time" datetime NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id"), "group_id" integer NOT NULL REFERENCES "auth_group" ("id"));
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "username" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id"), "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id"), "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id"));
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(80) NOT NULL UNIQUE);
CREATE INDEX "photologue_photosize_watermark_id_f9419f99" ON "photologue_photosize" ("watermark_id");
CREATE INDEX "photologue_photosize_effect_id_1d9b1b30" ON "photologue_photosize" ("effect_id");
CREATE INDEX "photologue_photo_sites_site_id_a26b734c" ON "photologue_photo_sites" ("site_id");
CREATE UNIQUE INDEX "photologue_photo_sites_photo_id_site_id_a8528863_uniq" ON "photologue_photo_sites" ("photo_id", "site_id");
CREATE INDEX "photologue_photo_sites_photo_id_1e4e4a98" ON "photologue_photo_sites" ("photo_id");
CREATE INDEX "photologue_photo_effect_id_5f27aba5" ON "photologue_photo" ("effect_id");
CREATE INDEX "photologue_gallery_sites_site_id_ff8bed9d" ON "photologue_gallery_sites" ("site_id");
CREATE UNIQUE INDEX "photologue_gallery_sites_gallery_id_site_id_4158504d_uniq" ON "photologue_gallery_sites" ("gallery_id", "site_id");
CREATE INDEX "photologue_gallery_sites_gallery_id_263bc875" ON "photologue_gallery_sites" ("gallery_id");
CREATE INDEX "photologue_gallery_photos_photo_id_38de5ebc" ON "photologue_gallery_photos" ("photo_id");
CREATE UNIQUE INDEX "photologue_gallery_photos_gallery_id_photo_id_ac3d7969_uniq" ON "photologue_gallery_photos" ("gallery_id", "photo_id");
CREATE INDEX "photologue_gallery_photos_gallery_id_770eac69" ON "photologue_gallery_photos" ("gallery_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
COMMIT;
