# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0002_imageinfo_videoinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoInfo',
            new_name='Image_Info',
        ),
        migrations.RenameModel(
            old_name='ImageInfo',
            new_name='Video_Info',
        ),
        migrations.RenameField(
            model_name='image_info',
            old_name='vdo_name',
            new_name='img_name',
        ),
        migrations.RenameField(
            model_name='video_info',
            old_name='img_name',
            new_name='vdo_name',
        ),
    ]
