# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0003_auto_20170930_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_Info',
        ),
        migrations.DeleteModel(
            name='Video_Info',
        ),
    ]
