# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twipic', '0005_imageinfo_videoinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageInfo',
        ),
        migrations.DeleteModel(
            name='VideoInfo',
        ),
    ]
